post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "jdoe",
    "password": "password"
}

###
post http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "jdoe",
  "password": "password"
}