post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "jdoe",
    "password": "password"
}

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Super User",
    "username": "superuser",
    "password": "secret"
}

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Abra Kadabdra",
    "username": "abkad",
    "password": "12345"
}


###
post http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "jdoe",
  "password": "password"
}

###
post http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "superuser",
  "password": "secret"
}

###
post http://localhost:3003/api/blogs/63b6be2ec3b201a31f7c9655/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlciIsIm5hbWUiOiJTdXBlciBVc2VyIiwiaWQiOiI2M2I1YWEzNmNjMDc1N2ZhZTZiMzk5YzciLCJpYXQiOjE2NzI5MjA2MzJ9.jdxjJPk8rCZBUUgmCiBY5XlkfrqKbQBi95v_tUSkdzQ

{
  "title": "Super Users blog post",
  "author": "Super User",
  "url": "www.test.com/hubba",
  "likes": 7,
  "comments": [
    "This is a comment",
    "This is another comment"
  ]
}

###
post http://localhost:3003/api/blogs/63b6bf1bc3b201a31f7c9673/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlciIsIm5hbWUiOiJTdXBlciBVc2VyIiwiaWQiOiI2M2I1YWEzNmNjMDc1N2ZhZTZiMzk5YzciLCJpYXQiOjE2NzI5MjA2MzJ9.jdxjJPk8rCZBUUgmCiBY5XlkfrqKbQBi95v_tUSkdzQ

{
  "title": "An awesome blog post",
  "author": "John Doe",
  "url": "www.test.com/1",
  "likes": 0,
  "comments": [
    "Such wow",
    "Awesome post",
    "I like this"
  ]
}